### ISSUE TITLE
\makeatletter and \makeatother should not be used in a .sty file

### ISSUE THREAD

**Issue by eg9** [charlesbaynham/globalvals#1]
As the title says, `\makeatletter` and `\makeatother` should not be used in `.sty` files. The former is implied, the latter could cause malfunction of other loaded packages.

**Comment by charlesbaynham** [comment]
Thanks for the tip! I've not got access to a computer right now but I'll tweak that once I do.

**Comment by charlesbaynham** [comment]
Fixed by a87e5a9447d21f06921d53df8ccb6d57aee88970
