### ISSUE TITLE
Typo in docs: \useVar instead of \useVal

### ISSUE THREAD

**Issue by daixtrose** [charlesbaynham/globalvals#3]
There is a typo [in the docs](https://github.com/charlesbaynham/globalvals/blob/master/globalvals/globalvals.tex#L55):

```latex
|\useVar{|\meta{key}|}|
```

instead of 
```latex
|\useVal{|\meta{key}|}|
```

**Comment by charlesbaynham** [comment]
Thanks @daixtrose, well spotted!
